server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://stage.icusin.com:3306/peking
    username: peking
    password: peking
    driveClassName: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:db/migration
    schemas: ['peking']
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
info:
  app:
    name: peking
    description: peking
    protocol: http
  version: 1.0.0
  contact:
    author: brinysoon
    email: brainysoon@gmail.com