server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://stage.icusin.com:3306/peking
    username: peking
    password: peking
    driveClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl